- name: Add target server
  command:
    cmd: |
      php /usr/local/ezlogin/ezwapi.php add_server \
        -api_url {{ ezeelogin_api_url }} \
        -secret '{{ ezeelogin_api_secret }}' \
        {{ lookup('template', 'server_addition.j2') }}
  register: server_addition
  changed_when: "'The server exists' not in server_addition.stdout"
  failed_when: "'error' in server_addition.stdout and 'The server exists' not in server_addition.stdout"
