---
# Ezeelogin does't provide an API to manage command guards (yet ?).
# Therefore, while it is ugly, command guards managment is done by updating the database directly.
- name: Install required python dependencies
  pip:
    name: "PyMySQL"
    executable: "{{ pip_executable }}"
    state: present

- name: Create or update command guards
  module_defaults:
    community.mysql.mysql_query:
      login_db: "{{ ezlogin_database_name }}"
      login_user: "{{ ezlogin_database_user | default(ezeelogin_mysql_super_user) }}"
      login_password: "{{ ezlogin_database_password | default(ezeelogin_mysql_super_user_password) }}"
      login_port: "{{ ezlogin_database_port | default(ezeelogin_mysql_server_port) }}"
      login_host: "{{ ezlogin_database_host | default(ezeelogin_mysql_server_host) }}"
  block:
    - set_fact:
        ezeelogin_command_guards_updated: false

    - name: Retrieve Ezeelogin command groups along with their IDs
      community.mysql.mysql_query:
        query: "SELECT id,name FROM {{ ezlogin_database_table_prefix }}_commandgroups;"
      register: query_result

    - name: Compute commandgroup name to ID dictionnary
      set_fact:
        commandgroup_name_id_dict: "{{ query_result.query_result[0] | items2dict(key_name='name', value_name='id') }}"

    - name: Retrieve Ezeelogin users along with their IDs
      community.mysql.mysql_query:
        query: "SELECT id,username FROM {{ ezlogin_database_table_prefix }}_users;"
      register: query_result

    - name: Compute user name to ID dictionnary
      set_fact:
        user_name_id_dict: "{{ query_result.query_result[0] | items2dict(key_name='username', value_name='id') }}"

    - name: Configure user command guards
      community.mysql.mysql_query:
        query:
          - "UPDATE {{ ezlogin_database_table_prefix }}_users \
             SET commandgroup_id={{ commandgroup_name_id_dict[item.command_group_name] }}, \
                 command_guard_type='{{ item.command_guard_type }}' \
             WHERE id={{ user_name_id_dict[item.username] }};"
          - "SELECT {{ label | quote }}"
      loop: "{{ ezeelogin_command_guards }}"
      loop_control:
        label: "{{ label }}"
      notify:
        - ezeelogin command guard update
      register: command_guard_updates
      vars:
        label: "Apply `{{ item.command_group_name }}` command guard to `{{ item.username }}`"

    - name: Compute command guard changes
      set_fact:
        ezeelogin_command_guard_changes: >-
          {{ command_guard_updates.results | selectattr('changed')
             | map(attribute='executed_queries')
             | map('last')
             | map('regex_replace', '^SELECT\s(.*)$', '\1') }}
