# See: https://www.ezeelogin.com/kb/article/5/how-to-install-ioncube-on-jump-server-7.html

- name: Download and unarchive ioncube loader
  unarchive:
    src: "{{ iocube_loader_url }}"
    dest: "{{ ioncube_installation_path | dirname}}"
    remote_src: yes
    creates: "{{ ioncube_installation_path }}"

- name: Configure ioncube as a Zend extension
  ini_file:
    path: "{{ item }}"
    section: PHP
    option: zend_extension
    value: "{{ ioncube_installation_path }}/ioncube_loader_lin_{{ php_version }}.so"
  loop:
    - "/etc/php/{{ php_version }}/apache2/php.ini"
    - "/etc/php/{{ php_version }}/cli/php.ini"
  notify: restart apache
